# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96.0"
authors = ["dotanuki.labs@gmail.com"]
description = "An utility that keeps your Github forks always in sync with upstreams"
repository = "https://github.com/dotanuki-labs/bellatrix"
homepage = "https://github.com/dotanuki-labs/bellatrix"
documentation = "https://github.com/dotanuki-labs/bellatrix"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]

[workspace.dependencies]
anyhow = "=1.0.102"
assert_cmd = "=2.2.2"
assertor = "=0.0.4"
async-trait = "0.1.89"
bellatrix-core = { version = "=0.1.0", path = "crates/bellatrix-core", registry = "local"}
better-panic = "=0.3.0"
clap = "=4.6.1"
console = "=0.16.3"
env_logger = "=0.11.10"
futures = "=0.3.32"
hex = "=0.4.3"
http = "=1.4.2"
httpmock = "=0.8.3"
human-panic = "=2.0.8"
log = "=0.4.32"
predicates = "=3.1.4"
reqwest = "=0.13.4"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
sha2 = "=0.11.0"
tikv-jemallocator = "=0.7.0"
tokio = "=1.52.3"
xshell = "=0.2.7"
walkdir = "=2.5.0"
worker = "=0.8.4"
worker-macros = "=0.8.4"

[workspace.lints.rust]
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = "deny"
rust_2018_idioms = "deny"
unsafe_code = "deny"
unnameable_types = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_qualifications = { level = "deny", priority = -1 }

[workspace.lints.clippy]
fallible_impl_from = "deny"
fn_params_excessive_bools = "deny"
indexing_slicing = "deny"
todo = "deny"
unimplemented = "deny"
unneeded_field_pattern = "deny"
unnested_or_patterns = "deny"
unwrap_used = "deny"
wildcard_enum_match_arm = "deny"
zero_sized_map_values = "deny"

[profile.release]
strip = true
lto = true
codegen-units = 1
