# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

[advisories]
ignore = [
    "RUSTSEC-2026-0044", # aws-lc-sys
    "RUSTSEC-2026-0048", # aws-lc-sys
    "RUSTSEC-2026-0049" # aws-lc-sys
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0"
]

