# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

[advisories]
ignore = [
    # add your stuff here
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0"
]

