# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "bellatrix-worker"
description = "A Cloudflare Worker that runs bellatrix"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
worker = { workspace = true, features = ['http'] }
bellatrix-core.workspace = true

[lints]
workspace = true

[profile.release]
lto = true
codegen-units = 1
