# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "bellatrix-core"
description = "Core functionality to sync Github forks with upstreams"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
log.workspace = true
reqwest = { workspace = true, features = ["json", "charset", "system-proxy", "http2"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
assertor.workspace = true
tokio = { workspace = true, features = ["full"] }


[lints]
workspace = true
